# load required packages and R scripts
library(Matrix)
library(spam)
library(fields)
library(LatticeKrig)
library(invgamma)
library(INLA)
library(latex2exp)
library(xtable)
library(profvis)
library(geosphere)
library(viridis)
library(sp)
library(raster)
library(MCMCpack)
library(numDeriv)

setwd("~/git/LK-INLA/")
source('compareModels.R')
source('LKinla.R')
source('LKinla_rgeneric.R')
source('modGP.R')
source('modSPDE.R')
source('modLKinla.R')
source('modLK.R')
source('modelResults.R')
source('getCommandArgs.R')
# source('mapOver.R')
source('utilityFuns.R')
# source('~/git/M9/exploratoryAnalysisFuns.R')

options(error=recover)